install: install-fpc.cmd
build_script: build.cmd
artifacts:
  - path: diskimage.zip
    name: pi disk image
  - path: kernel7.img
    name: pi needs 3 more files
cache:
  - c:\FPC -> appveyor.yml
  - c:\Ultibo -> appveyor.yml
skip_commits:
  files:
    - docs/**/*
    - README.md
