install: install-tools.cmd
build_script: build.cmd
artifacts:
  - path: diskimage.zip
    name: pi full disk image
  - path: kernel7.img.zip
    name: pi needs 3 more files
cache:
  - c:\FPC    -> install-tools.cmd
  - c:\Ultibo -> install-tools.cmd
  - bootfiles -> install-tools.cmd
skip_commits:
  files:
    - docs/**/*
    - README.md
