install: install-fpc.cmd
build_script: build.cmd
artifacts:
  - path: diskimage.zip
    name: ultibo
cache:
  - c:\FPC -> appveyor.yml
  - c:\Ultibo -> appveyor.yml
skip_commits:
  files:
    - docs/**/*
    - README.md
