install: install-fpc.cmd
build_script: build.cmd
artifacts:
  - path: diskimage.zip
    name: ultibo complete disk image
  - path: kernel7.img
    name: ultibo just kernel7.img - need other 3 files
cache:
  - c:\FPC -> appveyor.yml
  - c:\Ultibo -> appveyor.yml
skip_commits:
  files:
    - docs/**/*
    - README.md
