install: install-fpc.cmd
build_script: build.cmd
artifacts:
  - path: kernel7.img
    name: Ultibo
cache:
  - c:\FPC -> appveyor.yml
  - c:\Ultibo -> appveyor.yml
skip_commits:
  files:
    - docs/**/*
    - README.md
